repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: [black]
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: [--config=.flake8]
        additional_dependencies: [flake8]
