version: '3.8'
services:
  floriday:
    build: .
    container_name: floriday
    networks:
      - serra-vine
    volumes:
      - ./floridayvine-crontab:/etc/cron.d/floridayvine-crontab:ro
    env_file:
      - ./serra-vine.env
    environment:
      - TZ=UTC
    restart: on-failure

networks:
  serra-vine:
    external: true
