services:
  floridayvine:
    image: ghcr.io/serraict/vine-floriday-adapter:v0.12.2
    container_name: floridayvine
    depends_on:
      - mongo
    networks:
      - serra-vine
    env_file:
      - ./floridayvine/.env
    volumes:
      # mount your crontab file here:
      - ./floridayvine/floridayvine-crontab:/etc/cron.d/floridayvine-crontab:ro

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      serra-vine:
        aliases:
          - mongodb
          - api.mongodb
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./floridayvine/.env

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - serra-vine
    env_file:
      - ./floridayvine/.env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_OPTIONS_EDITORTHEME: default

networks:
  serra-vine:
    external: true

volumes:
  mongodb-data:
    driver: local
