# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Package

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FLORIDAY_CLIENT_ID: your_id
      FLORIDAY_CLIENT_SECRET: your_secret
      FLORIDAY_AUTH_URL: "https://idm.staging.floriday.io/oauth2/ausmw6b47z1BnlHkw0h7/v1/token"
      FLORIDAY_BASE_URL: "https://api.staging.floriday.io/suppliers-api-2024v1"
      FLORIDAY_API_KEY: your_api_key
      MONGODB_CONNECTION_STRING: "mongodb://your_user:your_password@localhost:27017"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        make update
    - name: Run quality checks
      run: |
        make quality
    - name: Set image tags
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/vine-floriday-adapter" >> $GITHUB_ENV
    - name: Package
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -t ${{ env.IMAGE_NAME }}:latest .
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Publish
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker push ${{ env.IMAGE_NAME }}:latest
